version: '2'
services:

  base:
    build:
      context: ./
      dockerfile: Dockerfile-base
      args:
        http_proxy:
    image: muccg/angelman-base

  builder:
    build:
      context: ./
      dockerfile: Dockerfile-builder
      args:
        ARG_GIT_TAG: ${GIT_TAG}
        http_proxy:
    image: muccg/angelman-builder
    command: releasetarball
    network_mode: host
    environment:
        GIT_TAG:
        PIP_INDEX_URL:
        PIP_TRUSTED_HOST:
        NO_PROXY:
    volumes:
      - ./build:/data

  dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        ARG_PIP_INDEX_URL: ${PIP_INDEX_URL}
        ARG_PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        http_proxy:
    image: muccg/angelman-dev
    volumes:
      - .:/app

  prod:
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        ARG_GIT_TAG: ${GIT_TAG}
        ARG_PIP_INDEX_URL: ${PIP_INDEX_URL}
        ARG_PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST}
        http_proxy:
    image: muccg/angelman:${GIT_TAG}
